### To get a pokemon by name
GET http://localhost:3000/pokemon/ditto

### To create a new pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
  "name": "Pikachu",
  "type": "electric",
  "moves": ["Attack Trueno"]
}